### ISSUE TITLE
RedProtect API

### ISSUE THREAD

**Issue by FabioZumbi12** [TheArchives/Painter#3]
I have maded some changes on Redprotect API 5.4.0. Dont forget to update your plugin to still working ;)

**Comment by gdude2002** [comment]
Thanks, I'll take a look.

**Comment by gdude2002** [comment]
Did you change all the packages?

**Comment by gdude2002** [comment]
Fixed in [this release](http://dev.bukkit.org/bukkit-plugins/painter/files/9-painter-0-0-4-plot-me-red-protect-fix/), once it's been approved.

Thanks for the ticket!
